name: esp_rainmaker_association
description: Native dart implementation of ESP Rainmaker provisioning and user mapping.
version: 1.0.0
homepage: https://github.com/chmoore889/esp_rainmaker_association

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3
  protobuf: ^2.0.0

dev_dependencies:
  lints: ^2.0.0
  pedantic: ^1.11.1
  uuid: ^3.0.4
