name: esp_rainmaker_association
description: Native dart implementation of ESP Rainmaker provisioning and user mapping.
version: 0.0.1-dev.1
homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  http: ^0.12.2
  protobuf: ^1.1.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  uuid: ^2.2.2
